/*b)Create a C++ class MyFile with data members file pointer and filename. Write necessary member functions to accept and disp lay File. Overload the following operators:
 
Operator       Example                 Purpose
+           F3= FI +F2   Concatenate the contents of file F1 and F2 in F3.
!                   F3    Changes the case of alternate characters of file F3.*/
#include<iostream.h>
#include<conio.h>
#include<stdlib.h>
#include<fstream.h>
#include<ctype.h>